import { formatContinuationContext, validateCompression } from "../core/Compression.js";
const labels = { healthy: ["Healthy", "🟢"], lengthy: ["Getting lengthy", "🟡"], fresh: ["Consider starting fresh", "🔴"] };

export class Overlay {
  constructor(actions) { this.actions = actions; this.host = document.createElement("div"); this.host.id = "contextflow-root"; this.shadow = this.host.attachShadow({ mode: "closed" }); document.documentElement.append(this.host); this.render(); }
  render() { this.shadow.replaceChildren(this.styles(), document.createElement("section")); this.panel = this.shadow.querySelector("section"); }
  styles() { const style = document.createElement("style"); style.textContent = `:host{all:initial}section{font:13px/1.4 system-ui,sans-serif;position:fixed;right:20px;bottom:20px;z-index:2147483647;width:290px;background:#fff;color:#202124;border:1px solid #d9dce1;border-radius:12px;box-shadow:0 8px 26px #0002;padding:14px}h2{font-size:14px;margin:0 0 5px}p{margin:7px 0;color:#5f6368}button{font:inherit;border:0;border-radius:7px;padding:7px 10px;margin:8px 6px 0 0;cursor:pointer;background:#eef2ff;color:#273b88}button.secondary{background:transparent;color:#536071}textarea{box-sizing:border-box;width:100%;min-height:170px;resize:vertical;border:1px solid #c8ccd2;border-radius:7px;padding:8px;font:12px/1.4 ui-monospace,monospace}small{color:#697386}`; return style; }
  clear() { this.panel.replaceChildren(); }
  showHealth(analysis) { this.clear(); const [label, icon] = labels[analysis.health.state]; const hasMessages = analysis.messageCount > 0; const diagnostics = analysis.diagnostics; this.panel.append(this.el("h2", `${icon} Conversation ${label}`), this.el("p", hasMessages ? `Estimated context: ~${analysis.totalTokens.toLocaleString()} tokens` : "Start chatting and ContextFlow will estimate the visible context locally."), this.el("small", hasMessages && diagnostics?.mountedMessageCount < diagnostics?.observedMessageCount ? `Includes ${diagnostics.observedMessageCount} observed turns; ChatGPT has unloaded some older turns from the page.` : "Local approximation — not the model’s exact token count.")); if (analysis.health.recommendCompression) { this.panel.append(this.el("p", "A fresh conversation may reduce unnecessary context."), this.button("Compress & Continue", () => this.actions.compress()), this.button("Keep chatting", () => this.hide(), "secondary")); } }
  showUnsupported() { this.clear(); this.panel.append(this.el("h2", "ContextFlow"), this.el("p", "This ChatGPT interface version isn't currently supported.")); }
  showStartupError() { this.clear(); this.panel.append(this.el("h2", "ContextFlow"), this.el("p", "ContextFlow could not initialize. Reload this page after reloading the extension.")); }
  showCompressionWaiting() { this.clear(); this.panel.append(this.el("h2", "Preparing continuation context"), this.el("p", "The instruction was inserted into ChatGPT. Send it, then use “Capture response” below once the response is complete."), this.button("Capture response", () => this.actions.capture()), this.button("Cancel", () => this.actions.cancel(), "secondary")); }
  showPreview(context, originalTokens) { const check = validateCompression(context, originalTokens); this.clear(); const area = document.createElement("textarea"); area.value = context; this.panel.append(this.el("h2", "Continuation Context"), area, this.el("p", `Original: ~${originalTokens.toLocaleString()} tokens · Context: ~${check.tokens.toLocaleString()} · Reduction: ~${Math.round(check.reduction * 100)}%`)); if (check.reason === "large") this.panel.append(this.el("p", "This context is still relatively large. Edit it or ask ChatGPT to compress again.")); this.panel.append(this.button("Start New Chat", () => this.actions.startNew(area.value)), this.button("Copy", async () => navigator.clipboard.writeText(formatContinuationContext(area.value))), this.button("Cancel", () => this.actions.cancel(), "secondary")); }
  showPromptCoach(suggestions) { if (!suggestions.length || this.panel.childElementCount) return; this.panel.append(this.el("h2", "Prompt may be underspecified"), this.el("p", suggestions.map((item) => `• ${item}`).join("\n"))); }
  hide() { this.host.style.display = "none"; }
  reveal() { this.host.style.display = "block"; }
  button(label, handler, className = "") { const button = this.el("button", label); button.className = className; button.addEventListener("click", handler); return button; }
  el(tag, text) { const element = document.createElement(tag); element.textContent = text; return element; }
}
